name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 在此添加構建、測試等步驟

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2.0
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
        with:
          args: '{"text": "Code pushed to master!"}'
